services:
  app:
    container_name: toidilam-prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=prod
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/toidilam?schema=public
      - REDIS_URL=redis://redis:6379
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - postgres
      - redis
    networks:
      - toidilam-network

volumes:
  postgres_data:
  redis_data:

networks:
  toidilam-network:
    driver: bridge
