name: CI - Build, Lint, Test

on:
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  lint:
    needs: setup
    runs-on: ubuntu-latest
    if: >
      ${{ (github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'chore:')) ||
         (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.title, 'chore:')) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4

      - name: Run lint
        run: pnpm lint

  build:
    needs: setup
    runs-on: ubuntu-latest
    if: >
      ${{ (github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'chore:')) ||
         (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.title, 'chore:')) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4

      - name: Run build
        run: pnpm build

  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   if: >
  #     ${{ (github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'chore:')) ||
  #        (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.title, 'chore:')) }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'pnpm'

  #     - uses: pnpm/action-setup@v4

  #     - name: Run tests
  #       run: pnpm test
