name: CI - Build, Lint, Test

on:
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pnpm-cache-path: ~/.pnpm-store
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
  lint:
    needs: setup
    runs-on: ubuntu-latest
    if: >
      ${{ (github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'chore:')) || (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.title, 'chore:')) }}
    steps:
      - uses: actions/checkout@v4
      - run: pnpm lint

  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #//   if: ${{ !startsWith(github.event.head_commit.message, 'chore:') }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: pnpm test

  build:
    needs: setup
    runs-on: ubuntu-latest
    if: >
      ${{ (github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'chore:')) || (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.title, 'chore:')) }}
    steps:
      - uses: actions/checkout@v4
      - run: pnpm build
